name: Testing

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: docker build .
